<?php

class FirstClass1 {

    public function __get($name) {
        $method_name = 'get' . ucfirst($name);
        return $this->$method_name();
    }

    public function __set($name, $value) {
        $method_name = 'set' . ucfirst($name);
        $this->$method_name($value);
    }

}

class TableCell1 {

    public $header;
    public $class;
    public $value;

    public function __construct($header, $class, $data) {
        $this->header = $header;
        $this->class = $class;
        $this->data = $data;
    }

}

